### ISSUE TITLE
CSV parser and excel parsers works different.

### ISSUE THREAD

**Issue by rockneurotiko** [AlexKovalevych/exoffice#10]
While doing #9 I found that the CSV parser and both excel parsers works different.

- CSV uses `CSV.decode/1` and thus get_rows returns:
```
[{:ok, [cols...]}, {:ok, [cols...]}]
```

- Excel parsers returns:
```
[[cols...], [cols...]]
```

I think what happened:
- This project started using `CSV` version 1.x, which decode returned the rows as the excel parsers
- In this commit, CSV version was upgraded from 1.x to 2.x: https://github.com/AlexKovalevych/exoffice/commit/c8e24569e7c07297d681e04137a7f7dbe3c704aa
The 2.x version added `decode!` and `decode` methods, as you can see here, they say to change to `decode!` in the upgrade: https://github.com/beatrichartz/csv#from-1x-to-2x---the-tasty-tm-update

So.. I think it makes sense to have homogeneity in the `get_rows` methods, and I think that the change to `CSV.decode!/1` makes more sense than change all the others to return `[{:ok, [cols..]}, ..]`

**Comment by danielRomero** [comment]
The issue can be closed, was solved in #11
